### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by ghost** [BasiliusCarver/TicTacTOBOL#1]

**Comment by ShaunLawrie** [comment]
I have some instruction at the bottom of the readme at https://github.com/BasiliusCarver/TicTacTOBOL#how-to-play  

In an Ubuntu machine you can install open-cobol with `sudo apt install open-cobol`  
Clone the repo with `git clone https://github.com/BasiliusCarver/TicTacTOBOL.git`  
Change into the repo directory with `cd TicTacTOBOL`  
Compile the TicTacTOBOL.cbl file with `cobc -W -x -o TicTacTOBOL TicTacTOBOL.cbl`  
Then run the application with `./TicTacTOBOL`

**Comment by ghost** [comment]
Can't I run online?

**Comment by ShaunLawrie** [comment]
It won't be easy to run online because I can't find any online COBOL compilers that can prompt you for input to make moves.
Here's one that kind of works but you have to make all the move choices in the STDIN tab and I quickly hacked together a version that works without a real terminal display.

http://tpcg.io/28wFoKOu
Before you click "execute" paste some input into the STDIN tab e.g.
```a1
a2
a3
b1
b2
b3
c1
c2
c3
```

**Comment by ghost** [comment]
works! thanks man!!
